# at centos6.7

splash:
  image: scrapinghub/splash:latest
  ports:
    - "5023:5023"
    - "8050:8050"
    - "8051:8051"

mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=rooT555_
    - MYSQL_DATABASE=exsongs
  volumes:
    - ~/docker/mysql5.7:/var/lib/mysql
  command: --character-set-server=utf8

mecab:
  image: bungoume/mecab-web-api:latest
  ports:
    - "8000:8000"

golang:
  image: golang:1.5
  links:
    - splash
    - mysql
    - mecab
  volumes:
    - ~/docker/golang1.5:/go
  entrypoint: ""
  command: >
    bash -c "
    go get -v github.com/yneee/exsongs/cmd &&
    cd /go/src/github.com/yneee/exsongs/cmd &&
    go get . &&
    go run /go/src/github.com/yneee/exsongs/cmd/exsongs.go
    "
