# at centos6.7

splash:
  hostname: splash
  image: scrapinghub/splash
  ports:
    - "5023:5023"
    - "8050:8050"
    - "8051:8051"

mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=rooT555_
    - MYSQL_DATABASE=exsongs
  volumes:
    - ~/docker/mysql5.7:/var/lib/mysql

golang:
  hostname: golang
  image: golang:1.5
  links:
    - splash
    - mysql
  volumes:
    - ~/docker/golang1.5:/go
  command: >
    bash -c "
    go get -v github.com/go-sql-driver/mysql &&
    go get -v github.com/jinzhu/gorm &&
    go get -v github.com/PuerkitoBio/goquery &&
    go get -v golang.org/x/crypto/bcrypt &&
    go get -v golang.org/x/text/encoding/japanese &&
    go get -v golang.org/x/text/transform &&
    go get -v github.com/yneee/exsongs
    go run src/github.com/yneee/exsongs/migrate_cli/migrate_cli.go &&
    go run src/github.com/yneee/exsongs/songs_cli/songs_cli.go
    "
