# at centos6.7

splash:
  image: scrapinghub/splash:latest
  ports:
    - "5023:5023"
    - "8050:8050"
    - "8051:8051"

mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=rooT555_
    - MYSQL_DATABASE=exsongs
  volumes:
    - ~/docker/mysql5.7:/var/lib/mysql
  command: --character-set-server=utf8

# need install plugins.
# docker exec exsongs_elasticsearch_1 /usr/share/elasticsearch/bin/plugin install analysis-kuromoji
elasticsearch:
  image: elasticsearch:2.1
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - ~/docker/elasticsearch2.1/data:/usr/share/elasticsearch/data
    - ~/docker/elasticsearch2.1/plugins:/usr/share/elasticsearch/plugins

golang:
  image: golang:1.5
  links:
    - splash
    - mysql
    - elasticsearch
  volumes:
    - ~/docker/golang1.5:/go
    - .:/go/src/github.com/yneee/exsongs
  entrypoint: ""
  command: go run /go/src/github.com/yneee/exsongs/cmd/exsongs.go
