# at centos6.7

splash:
  hostname: splash
  image: scrapinghub/splash
  ports:
    - "5023:5023"
    - "8050:8050"
    - "8051:8051"

mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=rooT555_
    - MYSQL_DATABASE=exsongs
  volumes:
    - ~/docker/mysql5.7:/var/lib/mysql
  command: --character-set-server=utf8

golang:
  hostname: golang
  image: golang:1.5
  links:
    - splash
    - mysql
  volumes:
    - ~/docker/golang1.5:/go
  entrypoint: ""
  command: >
    bash -c "
    go get -v github.com/yneee/exsongs/cmd &&
    cd src/github.com/yneee/exsongs/cmd &&
    go get . &&
    cd /go &&
    go run src/github.com/yneee/exsongs/cmd/exsongs.go
    "
